=== YuSharonmini/La-elite/videojuegos.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT VIDEOJUEGOS (GENERO)+>
	<!ATTLIST VIDEOJUEGOS xmlns:html CDATA #FIXED "http://www.w3.org/1999/xhtml">
<!ELEMENT GENERO (videojuego)+>
	<!ATTLIST GENERO genero ID #REQUIRED>
<!ELEMENT videojuego (titulo,tiendas,idiomas, dificultad, edad_recomendada, plataformas, 
online, anho_de_lanzamiento, desarrolladores*, empresa*, breve_descripcion, resenhas*, valoracion, curiosidades*)>
	<!ELEMENT titulo (#PCDATA)>
		<!ATTLIST titulo 
		imagen CDATA #IMPLIED
		version_juego CDATA #REQUIRED
		duracion CDATA #IMPLIED>
	<!ELEMENT tiendas (tienda)+>
		<!ELEMENT tienda (#PCDATA|window)*>
			<!ATTLIST tienda precio CDATA #REQUIRED 
		moneda CDATA #REQUIRED>
		<!ELEMENT window (html:a|html:embed)>
			<!ELEMENT html:a (#PCDATA)>
				<!ATTLIST html:a href CDATA #REQUIRED 
			target CDATA #REQUIRED>
			<!ELEMENT html:embed (#PCDATA)>
				<!ATTLIST html:embed src CDATA #REQUIRED 
			frameborder CDATA #REQUIRED 
			width CDATA #REQUIRED 
			height CDATA #REQUIRED>
	<!ELEMENT idiomas (idioma+)>
		<!ELEMENT idioma (#PCDATA)>
	<!ELEMENT dificultad (#PCDATA)>
	<!ELEMENT edad_recomendada (#PCDATA)>
		<!ATTLIST edad_recomendada pegi CDATA #REQUIRED>
	<!ELEMENT plataformas (plataforma+)>
		<!ELEMENT plataforma (#PCDATA)>
			<!ATTLIST plataforma mando CDATA #REQUIRED
		volante CDATA #REQUIRED>
	<!ELEMENT online (#PCDATA)>
	<!ELEMENT anho_de_lanzamiento (#PCDATA)>
	<!ELEMENT desarrolladores (desarrollador+)>
		<!ELEMENT desarrollador (#PCDATA)>
			<!ATTLIST desarrollador pais_de_origen CDATA #IMPLIED>
	<!ELEMENT empresa (#PCDATA)>
	<!ELEMENT breve_descripcion (#PCDATA)>
	<!ELEMENT resenhas (#PCDATA)>
	<!ELEMENT valoracion (#PCDATA)>
	<!ELEMENT curiosidades (curiosidad+)>
		<!ELEMENT curiosidad (#PCDATA)>

=== YuSharonmini/La-elite/Videojuegos.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="estilos/Videojuegos.css"?>
<!--<!DOCTYPE VIDEOJUEGOS SYSTEM "Videojuegos.dtd">-->
<!DOCTYPE VIDEOJUEGOS [
<!ELEMENT VIDEOJUEGOS (videojuego)+>
<!ELEMENT videojuego (titulo, tienda, idiomas, genero, dificultad, edad_recomendada, plataformas, 
online, anho_de_lanzamiento, desarrolladores*, empresa*, breve_descripcion, resenhas*, valoracion, curiosidades*)>
	<!ELEMENT titulo (#PCDATA)>
		<!ATTLIST titulo version_juego ID #REQUIRED
		duracion CDATA #IMPLIED>
	<!ELEMENT tienda (#PCDATA)>
		<!ATTLIST tienda precio CDATA #REQUIRED 
		 moneda CDATA #REQUIRED>
	<!ELEMENT idiomas (idioma+)>
		<!ELEMENT idioma (#PCDATA)>
	<!ELEMENT genero (#PCDATA)>
	<!ELEMENT dificultad (#PCDATA)>
	<!ELEMENT edad_recomendada (#PCDATA)>
	<!ELEMENT plataformas (plataforma+)>
		<!ELEMENT plataforma (#PCDATA)>
			<!ATTLIST plataforma mando CDATA #IMPLIED>
	<!ELEMENT online (#PCDATA)>
	<!ELEMENT anho_de_lanzamiento (#PCDATA)>
	<!ELEMENT desarrolladores (desarrollador+)>
		<!ELEMENT desarrollador (#PCDATA)>
			<!ATTLIST desarrollador pais_de_origen CDATA #IMPLIED>
	<!ELEMENT empresa (#PCDATA)>
	<!ELEMENT breve_descripcion (#PCDATA)>
	<!ELEMENT resenhas (#PCDATA)>
	<!ELEMENT valoracion (#PCDATA)>
	<!ELEMENT curiosidades (curiosidad+)>
		<!ELEMENT curiosidad (#PCDATA)>
]>

<VIDEOJUEGOS>
	<videojuego>
		<titulo version_juego="v1.9.2" duracion=""></titulo> 
		<tienda precio="" moneda=""></tienda><!--Link compra videojuego-->
		<idiomas>
			<idioma></idioma>
			<idioma></idioma>
		</idiomas>
		<genero></genero>
		<dificultad></dificultad>
		<edad_recomendada></edad_recomendada>
		<plataformas> <!--Que plataformas soporta-->
			<plataforma mando=""></plataforma>
			<plataforma mando=""></plataforma>
		</plataformas>
		<online></online>
		<anho_de_lanzamiento></anho_de_lanzamiento>
		<desarrolladores>
			<desarrollador pais_de_origen=""></desarrollador>
			<desarrollador pais_de_origen=""></desarrollador>
		</desarrolladores>
		<empresa></empresa> <!--Empresa que vende el juego-->
		<breve_descripcion></breve_descripcion>
		<resenhas></resenhas>
		<valoracion></valoracion>
		<curiosidades>
			<curiosidad></curiosidad>
			<curiosidad></curiosidad>
		</curiosidades>
	</videojuego>
</VIDEOJUEGOS>

=== YuSharonmini/La-elite/Ejemplo/Ejemplo/Videojuegos.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="estilos/Videojuegos.css"?>
<!DOCTYPE VIDEOJUEGOS SYSTEM "Videojuegos.dtd">


<VIDEOJUEGOS>
	<videojuego>
		<titulo version_juego="v1.9.2" duracion="">Minecraft</titulo> 
		<tienda precio="14,99" moneda="E">Steam</tienda><!--Link compra videojuego-->
		<idiomas>
			<idioma>Español</idioma>
			<idioma>Inglés</idioma>
		</idiomas>
		<genero>Plataforma</genero>
		<dificultad>10/10</dificultad>
		<edad_recomendada>18+</edad_recomendada>
		<plataformas> <!--Que plataformas soporta-->
			<plataforma mando="Mando XBOX">XBOX 360</plataforma>
			<plataforma mando="Teclado y raton">PC</plataforma>
		</plataformas>
		<online>Si</online>
		<anho_de_lanzamiento>1990</anho_de_lanzamiento>
		<desarrolladores>
			<desarrollador pais_de_origen="España">Mariano Rajoy</desarrollador>
			<desarrollador pais_de_origen="Andorra">Pedro Sánchez</desarrollador>
		</desarrolladores>
		<empresa>Majong</empresa> <!--Empresa que vende el juego-->
		<breve_descripcion>Un juego de bloques pa niños</breve_descripcion>
		<resenhas>Sí</resenhas>
		<valoracion>4/5</valoracion>
		<curiosidades>
			<curiosidad>No hay cuadrados</curiosidad>
			<curiosidad>Programado en Java</curiosidad>
		</curiosidades>
	</videojuego>
	
	<videojuego>
		<titulo version_juego="v1.9.3" duracion="">Minecraft</titulo> 
		<tienda precio="14,99" moneda="E">Steam</tienda><!--Link compra videojuego-->
		<idiomas>
			<idioma>Español</idioma>
			<idioma>Inglés</idioma>
		</idiomas>
		<genero>Plataforma</genero>
		<dificultad>10/10</dificultad>
		<edad_recomendada>18+</edad_recomendada>
		<plataformas> <!--Que plataformas soporta-->
			<plataforma mando="Mando XBOX">XBOX 360</plataforma>
			<plataforma mando="Teclado y raton">PC</plataforma>
		</plataformas>
		<online>Si</online>
		<anho_de_lanzamiento>1990</anho_de_lanzamiento>
		<desarrolladores>
			<desarrollador pais_de_origen="España">Mariano Rajoy</desarrollador>
			<desarrollador pais_de_origen="Andorra">Pedro Sánchez</desarrollador>
		</desarrolladores>
		<empresa>Majong</empresa> <!--Empresa que vende el juego-->
		<breve_descripcion>Un juego de bloques pa niños</breve_descripcion>
		<resenhas>Sí</resenhas>
		<valoracion>4/5</valoracion>
		<curiosidades>
			<curiosidad>No hay cuadrados</curiosidad>
			<curiosidad>Programado en Java</curiosidad>
		</curiosidades>
	</videojuego>
	
	<videojuego>
		<titulo version_juego="v1.9.4" duracion="">Minecraft</titulo> 
		<tienda precio="14,99" moneda="E">Steam</tienda><!--Link compra videojuego-->
		<idiomas>
			<idioma>Español</idioma>
			<idioma>Inglés</idioma>
		</idiomas>
		<genero>Plataforma</genero>
		<dificultad>10/10</dificultad>
		<edad_recomendada>18+</edad_recomendada>
		<plataformas> <!--Que plataformas soporta-->
			<plataforma mando="Mando XBOX">XBOX 360</plataforma>
			<plataforma mando="Teclado y raton">PC</plataforma>
		</plataformas>
		<online>Si</online>
		<anho_de_lanzamiento>1990</anho_de_lanzamiento>
		<desarrolladores>
			<desarrollador pais_de_origen="España">Mariano Rajoy</desarrollador>
			<desarrollador pais_de_origen="Andorra">Pedro Sánchez</desarrollador>
		</desarrolladores>
		<empresa>Majong</empresa> <!--Empresa que vende el juego-->
		<breve_descripcion>Un juego de bloques pa niños</breve_descripcion>
		<resenhas>Sí</resenhas>
		<valoracion>4/5</valoracion>
		<curiosidades>
			<curiosidad>No hay cuadrados</curiosidad>
			<curiosidad>Programado en Java</curiosidad>
		</curiosidades>
	</videojuego>
	
	<videojuego>
		<titulo version_juego="v1.9.5" duracion="">Minecraft</titulo> 
		<tienda precio="14,99" moneda="E">Steam</tienda><!--Link compra videojuego-->
		<idiomas>
			<idioma>Español</idioma>
			<idioma>Inglés</idioma>
		</idiomas>
		<genero>Plataforma</genero>
		<dificultad>10/10</dificultad>
		<edad_recomendada>18+</edad_recomendada>
		<plataformas> <!--Que plataformas soporta-->
			<plataforma mando="Mando XBOX">XBOX 360</plataforma>
			<plataforma mando="Teclado y raton">PC</plataforma>
		</plataformas>
		<online>Si</online>
		<anho_de_lanzamiento>1990</anho_de_lanzamiento>
		<desarrolladores>
			<desarrollador pais_de_origen="España">Mariano Rajoy</desarrollador>
			<desarrollador pais_de_origen="Andorra">Pedro Sánchez</desarrollador>
		</desarrolladores>
		<empresa>Majong</empresa> <!--Empresa que vende el juego-->
		<breve_descripcion>Un juego de bloques pa niños</breve_descripcion>
		<resenhas>Sí</resenhas>
		<valoracion>4/5</valoracion>
		<curiosidades>
			<curiosidad>No hay cuadrados</curiosidad>
			<curiosidad>Programado en Java</curiosidad>
		</curiosidades>
	</videojuego>
</VIDEOJUEGOS>
